/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'views' : bigint,
  'publishedDate' : string,
  'author' : string,
  'likes' : bigint,
  'summary' : string,
  'imageUrl' : string,
  'category' : Category,
}
export type Category = { 'incidents' : null } |
  { 'internationalNews' : null } |
  { 'cricket' : null } |
  { 'nationalNews' : null } |
  { 'influencers' : null } |
  { 'sports' : null };
export interface Comment {
  'id' : bigint,
  'createdAt' : string,
  'text' : string,
  'author' : string,
  'articleId' : bigint,
  'isPinned' : boolean,
}
export type Position = { 'mid' : null } |
  { 'top' : null } |
  { 'bottom' : null };
export interface Sponsor {
  'id' : bigint,
  'title' : string,
  'linkUrl' : string,
  'createdAt' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'position' : Position,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createArticle' : ActorMethod<
    [string, string, string, string, string, string, Category],
    bigint
  >,
  'createComment' : ActorMethod<[bigint, string, string, string], bigint>,
  'createSponsor' : ActorMethod<
    [string, string, string, Position, string],
    bigint
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteSponsor' : ActorMethod<[bigint], undefined>,
  'generateNewsArticle' : ActorMethod<[string, string, string, bigint], string>,
  'getActiveSponsorsByPosition' : ActorMethod<[Position], Array<Sponsor>>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllComments' : ActorMethod<[], Array<Comment>>,
  'getAllSponsors' : ActorMethod<[], Array<Sponsor>>,
  'getArticleById' : ActorMethod<[bigint], Article>,
  'getArticlesByCategory' : ActorMethod<[Category], Array<Article>>,
  'getCommentsByArticle' : ActorMethod<[bigint], Array<Comment>>,
  'getSponsorById' : ActorMethod<[bigint], Sponsor>,
  'likeArticle' : ActorMethod<[bigint], undefined>,
  'recordView' : ActorMethod<[bigint], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'togglePinComment' : ActorMethod<[bigint], undefined>,
  'toggleSponsorActive' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, string, string, string, string, Category],
    undefined
  >,
  'updateSponsor' : ActorMethod<
    [bigint, string, string, string, Position],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];